---
title: 'CoLab score: Summary dataset healthcare-worker population'
output:
  html_document: default
  pdf_document: default
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Import functions and variables.
```{r, include=FALSE, warning=FALSE, message=FALSE}
source('src/simulate_discordance.R', local = discordance <- new.env())
source('src/confusion_matrix.R', local = confusion <- new.env())
source('src/variables_colab.R', local = variables <- new.env())
source('src/predict_colab.R', local = colab <- new.env())
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(gt)
library(gtsummary)
```

```{r, echo=FALSE}
p2_5  <- function(x) quantile(x, probs = 0.025, names = FALSE)
p97_5 <- function(x) quantile(x, probs = 0.975, names = FALSE)
```

## Read data.
```{r}
parameters <- new.env()
parameters$data <- read.csv('data/colab_healthcare.csv')
parameters$identifier <- "visit_id"
parameters$continuous_prediction_function <- colab$get_continuous_prediction_colab
parameters$ordinal_prediction_function <- colab$get_ordinal_prediction_colab
parameters$categorical_prediction_function <- colab$get_categorical_prediction_colab
parameters$model <- NA
parameters$model_variables <- variables$selected_variables_colab
parameters$model_outcome <- "outcome"
```

## Calculate reference predictions.
```{r, echo=FALSE}
reference_predictions <- discordance$get_predictions(
  parameters$data, 
  parameters$identifier,
  parameters$continuous_prediction_function,
  parameters$ordinal_prediction_function,
  parameters$categorical_prediction_function,
  list(model_variables = parameters$model_variables)
)
```

```{r, echo=FALSE}
performance_measures <- confusion$get_summmary_performance_measures(
  reference_predictions,
  parameters$model_outcome,
  parameters$model_outcome_class_TRUE
)
```

## Summarise dataset.

- Distribution of predictive variables.
```{r, echo=FALSE}
parameters$data %>% tbl_summary(
  include = as.character(parameters$model_variables),
  statistic = all_continuous() ~ "{median} [{p2_5}; {p97_5}]",
  digits = everything() ~ 2
)
```

- Distribution of reference predictions.
```{r, echo=FALSE}
reference_predictions %>% tbl_summary(
  include = c(continuous_prediction, ordinal_prediction, categorical_prediction),
  statistic = all_continuous() ~ "{median} [{p2_5}; {p97_5}]",
  digits = everything() ~ 2
)
```

- Original performance measures.
```{r, echo=FALSE}
performance_measures %>% 
  pivot_longer(
    everything(),
    names_to = "performance_measure"
  ) %>%
  mutate(value = round(value, digits = 4)) %>% 
  gt() %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(
      cells_column_labels(columns = c(performance_measure, value))
    )
  )
```

