---
title: "CoLab Score: Discordant predictions related to bias in Zuyderland data"
output: html_document
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Import functions and variables.
```{r, include=FALSE, warning=FALSE, message=FALSE}
source('src/variables_colab.R', local = variables <- new.env())
source('src/predict_colab.R', local = colab <- new.env())

# temp
source('src/calculate_bias_table.r', local = bias <- new.env())
source('src/colab_specific_functions.R', local = colab_functions <- new.env()) # verwijderen

```

```{r}
library(tidyr)
```


## Set simulation parameters.
```{r}
parameters <- new.env()
parameters$data_with_log <- read.csv('data/CoLab_externe_validatie_Zuyderland.csv')
parameters$data <- colab_functions$colab_variable_de_log(parameters$data_with_log)

# ultra temp
parameters$data <- parameters$data %>%
                                group_by(Pat) %>%
                                slice(1) %>%
                                ungroup()

# ultra temp
parameters$identifier <- "Pat"
parameters$continuous_prediction_function <- colab$get_continuous_prediction_colab
parameters$ordinal_prediction_function <- colab$get_ordinal_prediction_colab
parameters$categorical_prediction_function <- colab$get_categorical_prediction_colab
parameters$model <- NA
parameters$model_variables <- variables$selected_variables_colab
parameters$uncertain_variables <- variables$selected_variables_colab[variables$uncertain_variables_indicator_colab]
parameters$laboratory <- "lab"
```

## Set SKML parameters

```{r}

# temp
parameters$SKML_data <- read.csv("data/paba_data.csv")
parameters$skml_names <- c( "Erytrocyten_BV" =  "Erytrocyten",
                            "Leukocyten_BV" = "Leukocyten",
                            "BilirubineTotaal_BV" = "Bilirubine",
                            "LD_BV" = "LD",
                            "AlkFosf_BV" = "Alk. Fosfatase",
                            "Albumine_BV" = "Albumine" ,
                            "GGT_BV" = "Gamma-GT",
                            "CRP_BV" = "CRP")

parameters$no_bias_variables <- parameters$model_variables[!parameters$model_variables %in% parameters$uncertain_variables]
parameters$ref_ptp <- 11 
parameters$bias_tables <- bias$get_bias_table(parameters$SKML_data,
                                              parameters$ref_ptp,
                                              parameters$skml_names,
                                              parameters$no_bias_variables)

parameters$bias_intercepts <- parameters$bias_tables$intercepts
parameters$bias_factors <- parameters$bias_tables$slopes

# temp


# parameters$SKML_data <- read.csv('data/paba_data.csv')
# parameters$SKML_names <- c("creatinine" = "Kreatinine")
# parameters$no_bias_variables <- parameters$model_variables[!parameters$model_variables %in% parameters$uncertain_variables]
# parameters$ref_ptp <- NA
# parameters$bias_tables <- skml$get_bias_table(parameters$SKML_data,
#                                               parameters$ref_ptp,
#                                               parameters$SKML_names,
#                                               parameters$no_bias_variables)
# parameters$bias_intercepts <- parameters$bias_tables$intercepts[1:3,]
# parameters$bias_factors <- parameters$bias_tables$slopes[1:3,]


```



## Set bootstrap parameters.
```{r}
parameters$bootstrap_number_of_samples <- 1000
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("perc") #c("norm", "perc")
```

## Set plot parameters.
```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_absolute_difference_binwidth <-  0.5
parameters$histogram_absolute_difference_x_range <- c(-10, 10)
parameters$histogram_absolute_difference_y_range <- c(0, 10)
parameters$histogram_percentage_difference_binwidth <-  0.5
parameters$histogram_percentage_difference_x_range <- c(-20, 20)
parameters$histogram_percentage_difference_y_range <- c(0, 10)
parameters$histogram_percentage_discordant_binwidth <-  0.5
parameters$histogram_percentage_discordant_x_range <- c(0, 20)
parameters$histogram_percentage_discordant_y_range <- c(0, 10)
```

## Set parameters to save results.
```{r}
# <<<<<<< Updated upstream
parameters$model_name <- 'colab'
parameters$population <- 'ed'
parameters$path_output <- 'out/colab/simulations_discordance/'
# =======
# parameters$path_and_name_simulated_results <- 'out/colab/simulations_discordance/colab_discordance_test_data_bias.csv'
# parameters$path_and_name_stats_with_ci <- 'out/colab/simulations_discordance/colab_discordance_test_data_stats_with_ci.csv'
# parameters$path_and_name_stats_without_ci <-
#   'out/colab/simulations_discordance/colab_discordance_test_data_stats_without_ci.csv'
# parameters$path_and_name_histogram_absolute_difference <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_absolute_difference.rds'
# parameters$path_and_name_histogram_percentage_difference <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_absolute_difference.rds'
# parameters$path_and_name_histogram_percentage_discordant <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_absolute_difference.rds'
# parameters$path_and_name_histogram_continuous_mae <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_continuous_mae.rds'
# parameters$path_and_name_histogram_continuous_rmse <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_continuous_rmse.rds'
# parameters$path_and_name_histogram_dichotomous_percentage_discordant <- 
#   'out/colab/simulations_discordance/colab_discordance_test_data_histogram_dichotomous_percentage_discordant.rds'
# 
# 
# 
# 
# >>>>>>> Stashed changes
```

```{r, child='markdown/template_discordance.Rmd'}

```
