---
title: "CoLab score: SA-based tolerance ranges for discordant predictions related to bias in healthcare-worker population"
output: html_document
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Import functions and variables.
```{r, include=FALSE, warning=FALSE, message=FALSE}
source('src/variables_colab.R', local = variables <- new.env())
source('src/predict_colab.R', local = colab <- new.env())
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
library(tidyr)
library(dplyr)
```

## Set simulation parameters.
```{r}
parameters <- new.env()
parameters$data <- read.csv('data/colab_healthcare.csv')
parameters$identifier <- "Pat"
parameters$continuous_prediction_function <- colab$get_continuous_prediction_colab
parameters$ordinal_prediction_function <- colab$get_ordinal_prediction_colab
parameters$categorical_prediction_function <- colab$get_categorical_prediction_colab
parameters$model <- NA
parameters$model_variables <- variables$selected_variables_colab
parameters$uncertain_variables <- variables$selected_variables_colab[variables$uncertain_variables_indicator_colab]
parameters$laboratory <- "lab"
```

## Set tolerance ranges for individual laboratory tests.
```{r}
tolerance_range_individual_tests_slopes <- list( 
  Erytrocyten_BV =      c((0.963), (1.037)),
  Leukocyten_BV =       c((0.921), (1.079)),
  BilirubineTotaal_BV = c((0.853), (1.141)),
  LD_BV =               c((0.893), (1.107)),
  AlkFosf_BV =          c((0.885), (1.115)),
  GGT_BV =              c((0.905), (1.095)),
  Albumine_BV =         c((0.917), (1.083)),
  CRP_BV =              c((0.845), (1.155))
)

all_combos_slopes <- expand.grid(tolerance_range_individual_tests_slopes)
all_combos_slopes <- all_combos_slopes %>%
  mutate(ptp = row_number(),
         age = NA,
         EosAbs_BV = NA,
         BasoAbs_BV = NA) # Set model variables without bias in de simulations to NA to reduce computation time.

tolerance_range_individual_tests_intercepts <- list(
  Erytrocyten_BV = c(0, 0),
  Leukocyten_BV = c(0, 0),
  BilirubineTotaal_BV = c(0, 0),
  LD_BV = c(0, 0),
  AlkFosf_BV = c(0, 0),
  GGT_BV = c(0, 0),
  Albumine_BV = c(0, 0),
  CRP_BV = c(0, 0)
)

all_combos_intercepts <- expand.grid(tolerance_range_individual_tests_intercepts)
all_combos_intercepts <- all_combos_intercepts %>%
  mutate(ptp = row_number(),
         age = NA,
         EosAbs_BV = NA,
         BasoAbs_BV = NA) # Set model variables without bias in de simulations to NA to reduce computation time.
```

```{r, echo=FALSE}
all_combos_slopes_long <- all_combos_slopes %>% 
  pivot_longer(
    cols = c(everything(), -ptp),
    names_to = "Bepaling",
    values_to = "Slope"
  )

all_combos_intercepts_long <- all_combos_intercepts %>% 
  pivot_longer(
    cols = c(everything(), -ptp),
    names_to = "Bepaling",
    values_to = "Intercept"
  )

all_combos_combined <- left_join(
  all_combos_intercepts_long,
  all_combos_slopes_long,
  by = c("ptp", "Bepaling")
)

all_combos_combined <- all_combos_combined %>%
  select(Bepaling, ptp, Intercept, Slope) %>%
  arrange(Bepaling)
```

## Set bias data parameters.
```{r}
parameters$bias_data <- all_combos_combined
parameters$bias_data_lab_col <- "ptp"
parameters$bias_data_cluster_col <- NA
parameters$bias_data_measurement_col <- "Bepaling"
parameters$bias_data_names <- c(
  "Erytrocyten_BV" =  "Erytrocyten_BV",
  "Leukocyten_BV" = "Leukocyten_BV",
  "BilirubineTotaal_BV" = "BilirubineTotaal_BV",
  "LD_BV" = "LD_BV",
  "AlkFosf_BV" = "AlkFosf_BV",
  "Albumine_BV" = "Albumine_BV" ,
  "GGT_BV" = "GGT_BV",
  "CRP_BV" = "CRP_BV"
)
parameters$bias_data_reference_lab <- NA
```

## Set bootstrap parameters for results of individual laboratories.
```{r}
parameters$bootstrap_number_of_samples <- NA
parameters$bootstrap_confidence_level <- NA
parameters$bootstrap_methods <- NA # choose from c("perc¨, "norm", "bca")
```

## Set plot parameters.
```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_continuous_median_prediction_binwidth <- 0.05
parameters$histogram_continuous_median_difference_binwidth <- 0.05
parameters$histogram_continuous_median_percentage_difference_binwidth <- 0.5
parameters$histogram_continuous_mae_binwidth <- 0.05
parameters$histogram_continuous_rmse_binwidth <- 0.05
parameters$histogram_continuous_mape_trimmed_binwidth <- 1
parameters$histogram_continuous_mdape_binwidth <- 1
parameters$histogram_continuous_rmspe_trimmed_binwidth <- 1
parameters$histogram_continuous_rmdspe_binwidth <- 1
parameters$histogram_ordinal_median_difference_binwidth <- 0.05
parameters$histogram_ordinal_mae_binwidth <- 0.05
parameters$histogram_ordinal_micro_rmse_binwidth <- 0.05
parameters$histogram_ordinal_macro_rmse_binwidth <- 0.05
parameters$histogram_ordinal_percentage_discordant_binwidth <- 1
parameters$histogram_categorical_percentage_discordant_binwidth <- 0.2
```

## Set parameters to save results.
```{r}
parameters$model_name <- 'colab'
parameters$population <- 'healthcare_tol_sa'
parameters$path_output <- 'out/colab/simulations_discordance/'
```

```{r, child='markdown/template_discordance.Rmd'}

```
