---
title: "CoLab score: Impact of bias related discordant predictions on crossover within confusion matrices based on simulations_discordance_aggregate_results"
output: html_document
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Load libraries.
```{r, include=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(tidyr)
library(purrr)
```

## Set main parameters.
```{r}
parameters <- new.env()
parameters$original_data <- read.csv('data/CoLab_externe_validatie_Zuyderland.csv')
parameters$discordance_data <- 
  read.csv('out/colab/simulations_discordance/colab_discordance_ed_bias_per_individual.csv')
parameters$identifier <- "id"
parameters$model_outcome <- "outcome"
parameters$model_outcome_class_TRUE <-  "1" 
parameters$model_prediction_class_TRUE <-  "percentage_TRUE"
```

## Set bootstrap parameters.
```{r}
parameters$bootstrap_number_of_samples <- 1000
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("perc") # c("norm", "bca")
```

## Set plot parameters.
```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_fn_minus_tp_percentage_point_diff_binwidth <-  0.5
parameters$histogram_fn_minus_tp_percentage_point_diff_x_range <- c(-10, 10)
parameters$histogram_fn_minus_tp_percentage_point_diff_y_range <- c(0, 10)
parameters$histogram_fp_minus_tn_percentage_point_diff_binwidth <-  0.5
parameters$histogram_fp_minus_tn_percentage_point_diff_x_range <- c(-10, 10)
parameters$histogram_fp_minus_tn_percentage_point_diff_y_range <- c(0, 10)
```

## Set parameters to save results.
```{r}
parameters$model_name <- 'colab'
parameters$population <- 'ed'
parameters$path_output <- 'out/colab/simulations_crossover/'
```

```{r, child='markdown/template_crossover.Rmd'}

```
