---
title: 'Friedewald: Summary dataset gp population (conventional units)'
output:
  html_document: default
  pdf_document: default
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Import functions and variables.
```{r, include=FALSE, warning=FALSE, message=FALSE}
source('src/simulate_discordance.R', local = discordance <- new.env())
source('src/variables_friedewald.R', local = variables <- new.env())
source('src/predict_friedewald_conventional.R', local = friedewald <- new.env())
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(gt)
library(gtsummary)
```

```{r, echo=FALSE}
p2_5  <- function(x) quantile(x, probs = 0.025, names = FALSE)
p97_5 <- function(x) quantile(x, probs = 0.975, names = FALSE)
```

## Read data.
```{r}
parameters <- new.env()
parameters$data <- read.csv('data/friedewald_gp.csv')
parameters$identifier <- "BezoekersID"
parameters$continuous_prediction_function <- friedewald$get_continuous_prediction_ldl
parameters$ordinal_prediction_function <- friedewald$get_ordinal_prediction_ldl
parameters$categorical_prediction_function <- friedewald$get_categorical_prediction_ldl
parameters$model <- NA
parameters$model_variables <- variables$selected_variables_friedewald
```

## Calculate reference predictions.
```{r, echo=FALSE}
reference_predictions <- discordance$get_reference_predictions(
  parameters$data, 
  parameters$identifier,
  parameters$continuous_prediction_function,
  parameters$ordinal_prediction_function,
  parameters$categorical_prediction_function,
  list(model_variables = parameters$model_variables)
)
```

## Summarise dataset.

```{r, echo=FALSE}
conversion_factors <- c(
  total_cholesterol = 38.67,
  hdl = 38.67,
  triglycerides = 88.5
)

```

- Distribution of predictive variables.
```{r, echo=FALSE}
parameters$data %>% 
  mutate(
    across(
      all_of(unname(parameters$model_variables)),
      ~ .x * conversion_factors[names(parameters$model_variables)[match(cur_column(), unname(parameters$model_variables))]]
    )
  ) %>% 
  tbl_summary(
    include = as.character(parameters$model_variables),
    statistic = all_continuous() ~ "{median} [{p2_5}; {p97_5}]",
    digits = everything() ~ 2
)
```

- Distribution of reference predictions.
```{r, echo=FALSE}
reference_predictions %>% tbl_summary(
  include = c(continuous_reference, ordinal_reference, categorical_reference),
  statistic = all_continuous() ~ "{median} [{p2_5}; {p97_5}]",
  digits = everything() ~ 2
)
```
