
```{r, include=FALSE, warning=FALSE, message=FALSE}
## Load libraries.
library(boot)
library(tidyr)
library(dplyr)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
## Import functions and variables.
source('src/confusion_matrix.R', local = confusion <- new.env())
source('src/bootstrapped_ci.R', local = bootstrapped <- new.env())
source('src/comparison.R', local = comparison <- new.env())
source('src/print_table.R', local = print <- new.env())
source('src/save_output.R', local = save <- new.env())
```

```{r, echo=FALSE}
## Combine dataframe with measured outcome.

discordance_status <- left_join(
  parameters$original_data %>% select(
    all_of(parameters$identifier), 
    all_of(parameters$model_outcome)
  ),
  parameters$discordance_data,
  by = parameters$identifier)
```

## Calculate crossover measures.

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), results = 'asis', echo=FALSE}
cat("The distribution of bootstrapped estimates and the bootstrap bias estimate determine the appropriateness of normal and percentile bootstrapped confidence intervals. Bias-corrected and accelerated (BCa) confidence intervals correct for bias and skewness in the distribution of bootstrapped estimates but require more computational time.")
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE}
bootstrapped_crossover <- 
  discordance_status %>%
  group_split(laboratory) %>%
  set_names(unlist(group_keys(discordance_status %>% group_by(laboratory)))) %>%
  purrr::map(
    function(x){
      boot(
        x,
        confusion$get_crossover_summary_as_vector,
        parameters$bootstrap_number_of_samples,
        outcome = parameters$model_outcome,
        outcome_class_TRUE = parameters$model_outcome_class_TRUE
      )
    }
  )
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), results = 'asis', echo=FALSE}
cat("-  Table with bootstrapped summary statistics:")
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE}
bootstrapped_ci_crossover <- bootstrapped$get_bootstrapped_ci_all_laboratories(
  bootstrapped_crossover,
  confusion$get_variables_names_from_crossover_summary_as_vector(
    discordance_status,
    parameters$model_outcome,
    parameters$model_outcome_class_TRUE), 
  parameters$bootstrap_confidence_level, 
  parameters$bootstrap_methods
)

save$save_summary(
  bootstrapped_ci_crossover, 
  parameters$path_output, 
  parameters$model_name, 
  "crossover",
  parameters$population,
  "stats_with_ci"
)

print$print_table_bootstrapped_summary(bootstrapped_ci_crossover, 4)
```

- Compact table with summary statistics.

```{r, eval = is.na(parameters$bootstrap_number_of_samples), echo=FALSE}
summary_crossover <- confusion$get_crossover_summary_all_laboratories(
  discordance_status,     
  parameters$model_outcome,
  parameters$model_outcome_class_TRUE
)

save$save_summary(
  summary_crossover, 
  parameters$path_output, 
  parameters$model_name, 
  "crossover",
  parameters$population,
  "stats_without_ci"
)

print$print_table_summary(summary_crossover, 4)
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE}
summary_crossover <- bootstrapped$get_dataframe_without_ci(bootstrapped_ci_crossover)

save$save_summary(
  summary_crossover, 
  parameters$path_output, 
  parameters$model_name, 
  "crossover",
  parameters$population,
  "stats_without_ci"
)

print$print_table_summary(summary_crossover, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of percentage point difference between the probability discordant FN negative and TP results:")

histogram_fn_minus_tp_percentage_point_diff <- comparison$get_histogram(
  summary_crossover, 
  "fn_minus_tp_percentage_point_diff",
  "Probability discordant false negative - true positive (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_fn_minus_tp_percentage_point_diff_binwidth,
  parameters$histogram_fn_minus_tp_percentage_point_diff_x_range,
  parameters$histogram_fn_minus_tp_percentage_point_diff_y_range
)

save$save_histogram(
  histogram_fn_minus_tp_percentage_point_diff, 
  parameters$path_output, 
  parameters$model_name, 
  "crossover",
  parameters$population
)

plot(histogram_fn_minus_tp_percentage_point_diff)
```

```{r, results = 'asis', echo=FALSE, message=FALSE}
distribution_fn_minus_tp_percentage_point_diff <- comparison$get_distribution_table(
  summary_crossover, 
  "fn_minus_tp_percentage_point_diff", 
  "laboratory"
)

print$print_table_distribution(distribution_fn_minus_tp_percentage_point_diff, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of percentage point difference between the probability discordant FP and TN results:")

histogram_fp_minus_tn_percentage_point_diff <- comparison$get_histogram(
  summary_crossover, 
  "fp_minus_tn_percentage_point_diff",
  "Probability discordant false positive - true negative (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_fp_minus_tn_percentage_point_diff_binwidth,
  parameters$histogram_fp_minus_tn_percentage_point_diff_x_range,
  parameters$histogram_fp_minus_tn_percentage_point_diff_y_range
)

save$save_histogram(
  histogram_fp_minus_tn_percentage_point_diff, 
  parameters$path_output, 
  parameters$model_name, 
  "crossover",
  parameters$population
)

plot(histogram_fp_minus_tn_percentage_point_diff)
```

```{r, results = 'asis', echo=FALSE, message=FALSE}
distribution_fp_minus_tn_percentage_point_diff <- comparison$get_distribution_table(
  summary_crossover, 
  "fp_minus_tn_percentage_point_diff", 
  "laboratory"
)

print$print_table_distribution(distribution_fp_minus_tn_percentage_point_diff, 4)
```