
```{r, include=FALSE, warning=FALSE, message=FALSE}
## Load libraries.
library(boot)
library(tidyr)
library(dplyr)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
## Import functions and variables.
source('src/confusion_matrix.R', local = confusion <- new.env())
source('src/bootstrapped_ci.R', local = bootstrapped <- new.env())
source('src/comparison.R', local = comparison <- new.env())
source('src/print_table.R', local = print <- new.env())
source('src/save_output.R', local = save <- new.env())
```

```{r, echo=FALSE}
## Combine dataframe with measured outcome.

discordance_status <- left_join(
  parameters$original_data %>% 
    select(
      all_of(parameters$identifier),
      all_of(parameters$model_outcome)
    ),
  parameters$discordance_data,
  by = parameters$identifier
)
```

## Calculate confusion matrix derived measures.

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), results = 'asis', echo=FALSE}
cat("The distribution of bootstrapped estimates and the bootstrap bias estimate determine the appropriateness of normal and percentile bootstrapped confidence intervals. Bias-corrected and accelerated (BCa) confidence intervals correct for bias and skewness in the distribution of bootstrapped estimates but require more computational time.")
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE, message=FALSE}
bootstrapped_performance_measures <- 
  discordance_status %>%
  group_split(laboratory) %>%
  set_names(unlist(group_keys(discordance_status %>% group_by(laboratory)))) %>%
  purrr::map(
    function(x){
      boot(
        x,
        confusion$get_summmary_performance_measures_as_vector,
        parameters$bootstrap_number_of_samples,
        outcome = parameters$model_outcome, 
        outcome_class_TRUE = parameters$model_outcome_class_TRUE
      )
    }
  )
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), results = 'asis', echo=FALSE}
cat("-  Table with bootstrapped summary statistics:")
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE, message=FALSE}
bootstrapped_ci_performance_measures <- bootstrapped$get_bootstrapped_ci_all_laboratories(
  bootstrapped_performance_measures,
  confusion$get_variable_names_from_summmary_performance_measures_as_vector(
    discordance_status,
    parameters$model_outcome, 
    parameters$model_outcome_class_TRUE
  ), 
  parameters$bootstrap_confidence_level, 
  parameters$bootstrap_methods
)

save$save_summary(
  bootstrapped_ci_performance_measures, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population,
  "stats_with_ci"
)

print$print_table_bootstrapped_summary(bootstrapped_ci_performance_measures, 4)
```

- Compact table with summary statistics.

```{r, eval = is.na(parameters$bootstrap_number_of_samples), echo=FALSE, message=FALSE}
summary_performance_measures <- confusion$get_summary_performance_measures_all_laboratories(
  discordance_status, 
  parameters$model_outcome, 
  parameters$model_outcome_class_TRUE
)

save$save_summary(
  summary_performance_measures, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population,
  "stats_without_ci"
)

print$print_table_summary(summary_performance_measures, 4)
```

```{r, eval = !is.na(parameters$bootstrap_number_of_samples), echo=FALSE}
summary_performance_measures <- bootstrapped$get_dataframe_without_ci(bootstrapped_ci_performance_measures)

save$save_summary(
  summary_performance_measures, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population,
  "stats_without_ci"
)

print$print_table_summary(summary_performance_measures, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of area under the receiver operating characteristic curve:")

histogram_auroc <- comparison$get_histogram(
  summary_performance_measures, 
  "auroc",
  "Area under the receiver operating characteristic curve",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_auroc_binwidth,
  parameters$histogram_auroc_x_range,
  parameters$histogram_auroc_y_range
)

save$save_histogram(
  histogram_auroc, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_auroc)
```

```{r, echo=FALSE, message=FALSE}
distribution_auroc <- comparison$get_distribution_table(
  summary_performance_measures, 
  "auroc", 
  "laboratory"
)

print$print_table_summary(distribution_auroc, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of accuracy:")

histogram_accuracy <- comparison$get_histogram(
  summary_performance_measures, 
  "accuracy",
  "Accuracy (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_accuracy_binwidth,
  parameters$histogram_accuracy_x_range,
  parameters$histogram_accuracy_y_range
)

save$save_histogram(
  histogram_accuracy, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_accuracy)
```

```{r, echo=FALSE, message=FALSE}
distribution_accuracy <- comparison$get_distribution_table(
  summary_performance_measures, 
  "accuracy", 
  "laboratory"
)

print$print_table_distribution(distribution_accuracy, 4)
```


```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of sensitivity:")

histogram_sensitivity <- comparison$get_histogram(
  summary_performance_measures, 
  "sensitivity",
  "Sensitivity (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_sensitivity_binwidth,
  parameters$histogram_sensitivity_x_range,
  parameters$histogram_sensitivity_y_range
)

save$save_histogram(
  histogram_sensitivity, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_sensitivity)
```

```{r, echo=FALSE, message=FALSE}
distribution_sensitivity <- comparison$get_distribution_table(
  summary_performance_measures, 
  "sensitivity", 
  "laboratory"
)

print$print_table_distribution(distribution_sensitivity, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of specificity:")

histogram_specificity <- comparison$get_histogram(
  summary_performance_measures, 
  "specificity",
  "specificity",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_specificity_binwidth,
  parameters$histogram_specificity_x_range,
  parameters$histogram_specificity_y_range
)

save$save_histogram(
  histogram_specificity, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_specificity)
```

```{r, echo=FALSE, message=FALSE}
distribution_specificity <- comparison$get_distribution_table(
  summary_performance_measures, 
  "specificity", 
  "laboratory"
)

print$print_table_distribution(distribution_specificity, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of positive predictive value:")

histogram_ppv <- comparison$get_histogram(
  summary_performance_measures, 
  "pos_pred_value",
  "Positive predictive value (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_ppv_binwidth,
  parameters$histogram_ppv_x_range,
  parameters$histogram_ppv_y_range
)

save$save_histogram(
  histogram_ppv, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_ppv)
```

```{r, echo=FALSE, message=FALSE}
distribution_ppv <- comparison$get_distribution_table(
  summary_performance_measures, 
  "pos_pred_value", 
  "laboratory"
)

print$print_table_distribution(distribution_ppv, 4)
```

```{r, results = 'asis', echo=FALSE}
cat("* Histogram and distribution of negative predictive value:")

histogram_npv <- comparison$get_histogram(
  summary_performance_measures, 
  "neg_pred_value",
  "Negative predictive value (%)",
  parameters$histogram_method,
  parameters$histogram_method_label,
  parameters$histogram_npv_binwidth,
  parameters$histogram_npv_x_range,
  parameters$histogram_npv_y_range
)

save$save_histogram(
  histogram_npv, 
  parameters$path_output, 
  parameters$model_name, 
  "confusion_matrix",
  parameters$population
)

plot(histogram_npv)
```

```{r, echo=FALSE, message=FALSE}
distribution_npv <- comparison$get_distribution_table(
  summary_performance_measures, 
  "neg_pred_value", 
  "laboratory"
)

print$print_table_distribution(distribution_npv, 4)
```
