---
title: 'eGFR: Discordant predictions related to bias in test_data'
output:
  html_document: default
  pdf_document: default
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Import functions and variables.

```{r, include=FALSE, warning=FALSE, message=FALSE}
source('src/variables.R', local = variables <- new.env())
source('src/predict_egfr.R', local = egfr <- new.env())
source('src/calculate_bias_table.r', local = skml <- new.env())
```

## Set simulation parameters.

```{r}
parameters <- new.env()
parameters$data <- read.csv('data/test_data.csv')
parameters$identifier <- "id"
parameters$continuous_prediction_function <- egfr$get_continuous_prediction_egfr
parameters$ordinal_prediction_function <- egfr$get_ordinal_prediction_egfr
parameters$categorical_prediction_function <- egfr$get_categorical_prediction_egfr
parameters$model <- NA
parameters$model_variables <- variables$selected_variables_egfr
parameters$uncertain_variables <- variables$selected_variables_egfr[variables$uncertain_variables_indicator_egfr]
parameters$laboratory <- "lab"
```

## Set SKML parameters

```{r}
parameters$SKML_data <- read.csv('data/paba_data.csv')
parameters$SKML_names <- c("creatinine" = "Kreatinine")
parameters$no_bias_variables <- parameters$model_variables[!parameters$model_variables %in% parameters$uncertain_variables]
parameters$ref_ptp <- NA
parameters$bias_tables <- skml$get_bias_table(parameters$SKML_data, 
                                              parameters$ref_ptp, 
                                              parameters$SKML_names, 
                                              parameters$no_bias_variables)
parameters$bias_intercepts <- parameters$bias_tables$intercepts[1:3,]
parameters$bias_factors <- parameters$bias_tables$slopes[1:3,]


```

## Set bootstrap parameters

```{r}
parameters$bootstrap_number_of_samples <- 100
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("perc")
```

## Set plot parameters.

```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_absolute_difference_binwidth <-  0.5
parameters$histogram_absolute_difference_x_range <- c(-10, 10)
parameters$histogram_absolute_difference_y_range <- c(0, 10)
parameters$histogram_percentage_difference_binwidth <-  0.5
parameters$histogram_percentage_difference_x_range <- c(-20, 20)
parameters$histogram_percentage_difference_y_range <- c(0, 10)
parameters$histogram_percentage_discordant_binwidth <-  0.5
parameters$histogram_percentage_discordant_x_range <- c(0, 20)
parameters$histogram_percentage_discordant_y_range <- c(0, 10)
```

## Set directories to save results.

```{r}
parameters$path_output <- 'out/egfr/simulations_discordance/'
parameters$path_and_name_simulated_results <- 'out/egfr/simulations_discordance/egfr_discordance_test_data_bias.csv'
parameters$path_and_name_stats_with_ci <- 'out/egfr/simulations_discordance/egfr_discordance_test_data_stats_with_ci.csv'
parameters$path_and_name_stats_without_ci <-
  'out/egfr/simulations_discordance/egfr_discordance_test_data_stats_without_ci.csv'
parameters$path_and_name_histogram_continuous_mae <- 
  'out/egfr/simulations_discordance/egfr_discordance_test_data_histogram_continuous_mae.rds'
parameters$path_and_name_histogram_continuous_rmse <- 
  'out/egfr/simulations_discordance/egfr_discordance_test_data_histogram_continuous_rmse.rds'
parameters$path_and_name_histogram_dichotomous_percentage_discordant <- 
  'out/egfr/simulations_discordance/egfr_discordance_test_data_histogram_dichotomous_percentage_discordant.rds'
```

```{r, child='markdown/template_discordance.Rmd'}

```
