---
title: "eGFR: Impact of bias related discordant predictions on crossover within confusion matrices based on simulations_discordance_aggregate_results"
output: html_document
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Load libraries.
```{r, include=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(tidyr)
library(purrr)
```

## Set main parameters.
```{r}
parameters <- new.env()
parameters$original_data <- read.csv('data/test_data.csv')
parameters$discordance_data <- 
  read.csv('out/egfr/simulations_discordance/egfr_discordance_gp_bias_per_individual.csv')
parameters$identifier <- "id"
parameters$model_outcome <- "mgfr_dichotomous"
parameters$model_outcome_class_TRUE <-  "1" 
```

## Set bootstrap parameters.
```{r}
parameters$bootstrap_number_of_samples <- 1000
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("perc")
```

## Set plot parameters.
```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_absolute_difference_binwidth <-  0.5
parameters$histogram_absolute_difference_x_range <- c(-10, 10)
parameters$histogram_absolute_difference_y_range <- c(0, 10)
parameters$histogram_percentage_difference_binwidth <-  0.5
parameters$histogram_percentage_difference_x_range <- c(-20, 20)
parameters$histogram_percentage_difference_y_range <- c(0, 10)
parameters$histogram_percentage_discordant_binwidth <-  0.5
parameters$histogram_percentage_discordant_x_range <- c(0, 20)
parameters$histogram_percentage_discordant_y_range <- c(0, 10)
```

## Set parameters to save results.
```{r}
parameters$model_name <- 'egfr'
parameters$population <- 'gp'
parameters$path_output <- 'out/egfr/simulations_crossover/'
```

```{r, child='markdown/template_crossover.Rmd'}

```
