---
title: "eGFR: Impact of bias on confusion matrices based on simulations_discordance"
output: html_document
date: "Report generated on: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
set.seed(seed = 200)
```

## Load libraries.

```{r, include=FALSE, warning=FALSE, message=FALSE}
library(DT)
library(tidyr)
library(purrr)
```

## Set main parameters.

```{r}
parameters <- new.env()
parameters$original_data <- read.csv('data/test_data.csv')
parameters$discordance_data <- 
  read.csv('out/egfr/simulations_discordance/egfr_discordance_test_data_bias.csv')
parameters$identifier <- "id"
parameters$model_outcome <- "mgfr_60"
parameters$model_outcome_class_TRUE <-  "1"
parameters$bootstrap_number_of_samples <- 1000
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("norm", "perc")
```

## Set bootstrap parameters.

```{r}
parameters$bootstrap_number_of_samples <- 1000
parameters$bootstrap_confidence_level <- 0.95
parameters$bootstrap_methods <- c("norm", "perc")
```

## Set plot parameters.

```{r}
parameters$histogram_method <- "laboratory"
parameters$histogram_method_label <- "Laboratory"
parameters$histogram_auroc_binwidth <-  0.02
parameters$histogram_auroc_x_range <- c(0.5, 1.0)
parameters$histogram_auroc_y_range <- c(0, 10)
parameters$histogram_sensitivity_binwidth <-  0.02
parameters$histogram_sensitivity_x_range <- c(0.0, 1.0)
parameters$histogram_sensitivity_y_range <- c(0, 10)
parameters$histogram_specificity_binwidth <-  0.02
parameters$histogram_specificity_x_range <- c(0.5, 1.0)
parameters$histogram_specificity_y_range <- c(0, 10)
```

## Set directories to save results.

```{r}
parameters$path_and_name_combined_stats <- 'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_bias_combined_stats.csv'
parameters$path_and_name_stats_with_ci <- 'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_bias_stats_with_ci.csv'
parameters$path_and_name_stats_without_ci <-
  'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_bias_stats_without_ci.csv'
parameters$path_and_name_histogram_auroc <- 
  'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_histogram_auroc.rds'
parameters$path_and_name_histogram_sensitivity <- 
  'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_histogram_sensitivity.rds'
parameters$path_and_name_histogram_specificity <- 
  'out/egfr/simulations_confusion_matrix/egfr_confusion_matrix_test_data_histogram_specificity.rds'
```

```{r, child='markdown/template_confusion_matrices.Rmd'}

```
